blank_issues_enabled: false
contact_links:
  - name: 💬 Trao đổi & Thảo luận
    url: https://github.com/OwnWallet/website_ownWallet/discussions
    about: Hãy đặt câu hỏi hoặc trao đổi ý tưởng tại GitHub Discussions.
